#! /bin/bash

VERSION="1.0.0"
DATE="26/09/2022"

echo "sintetizador-decomp"
echo "Gerência de Metodologias e Modelos Energéticos - PEM / ONS"
echo "Versão ${VERSION} - ${DATE}"

USERINSTALLDIR=/home/pem/rotinas
INSTALLDIR=${USERINSTALLDIR}/sintetizador-decomp

# Checks if application is installed
if [ ! -d $INSTALLDIR ]; then
    echo "Aplicação não encontrada..."
    exit 1
fi

RUN=$INSTALLDIR/main.py

echo "Ativando o ambiente virtual"
source $INSTALLDIR/venv/bin/activate

echo "Executando"
echo "------------------"

echo python3 $RUN $*
python3 $RUN $*

echo "------------------"
echo "Desativando o ambiente virtual"
deactivate